### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by bymayo** [CrewLabs/oauth2-dribbble#3]
Will you be able to make this work with Dribbble API v2?

http://developer.dribbble.com/changes/
http://developer.dribbble.com/v2/

I currently don't use this library, but I will need to because Dribbble API will require oAuth as of March 2018.

But I noticed your code currently still references v1

**Comment by pbyrne** [comment]
Sorry for the delay in responding to your question. We don't use this library ourselves any more, so are making a choice not to maintain it going forward. I'll note that the license of this repo is such that anyone who is interested in continuing to maintain it going forward is welcome to fork it and continue development.
